# Generated by Django 3.0.8 on 2020-07-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='simpleMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=16)),
                ('noam', models.IntegerField()),
                ('johnny', models.IntegerField()),
                ('moshe', models.IntegerField()),
                ('ahon', models.IntegerField()),
                ('dror', models.IntegerField()),
            ],
        ),
    ]
