# Generated by Django 3.0.8 on 2020-07-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypoker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=16)),
            ],
        ),
    ]
