# Generated by Django 3.0.8 on 2020-07-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypoker', '0003_simplemeeting_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplemeeting',
            name='ahon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simplemeeting',
            name='dror',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simplemeeting',
            name='johnny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simplemeeting',
            name='moshe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simplemeeting',
            name='noam',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SimpleGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noam', models.IntegerField(default=0)),
                ('johnny', models.IntegerField(default=0)),
                ('moshe', models.IntegerField(default=0)),
                ('ahon', models.IntegerField(default=0)),
                ('dror', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mypoker.simpleMeeting')),
            ],
        ),
    ]
