# Generated by Django 3.0.8 on 2020-07-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypoker', '0008_auto_20200713_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplemeeting',
            name='date',
        ),
    ]
