# Generated by Django 3.0.8 on 2020-07-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypoker', '0009_remove_simplemeeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemeeting',
            name='date',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
