# Generated by Django 3.0.8 on 2020-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypoker', '0010_simplemeeting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(blank=True, choices=[('FLASH', 'Flush'), ('FULL HOUSE', 'Full house'), ('FOUR OF A KIND', 'Four of a kind'), ('STRAIGHT FLUSH', 'Straight flush')], max_length=50)),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='simplemeeting',
            name='date',
            field=models.DateField(blank=True, default='2020-01-01'),
        ),
    ]
