# Generated by Django 3.0.8 on 2020-07-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypoker', '0014_hand_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplegame',
            old_name='johnny',
            new_name='johnny',
        ),
    ]
